config/routes.rb
Rails.application.routes.draw do
  get 'nav/index'

  get 'nav/add_row'

  get 'nav/calc_nav'
  post 'nav/calc_nav'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nav_history.rb
class NavHistory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nav_controller.rb
class NavController < ApplicationController
  def index
  	@@col = 1
    @scheme = NavHistory.select("distinct(scheme_name)").map(&:scheme_name).uniq
  end

  def add_row
  	@@col += 1
  	@col = @@col
    @scheme = NavHistory.select("distinct(scheme_name)").map(&:scheme_name).uniq
    p @col
    p @@col
    # render :json => {:col => @col}
  end

  def calc_nav
    p "11111111111111111"
  	@purchase_date = params['amt']
    puts "================================================="
    puts "date = #{@purchase_date}"
    @inv_amt = params["amt_1"]
  	@scheme_name = params["scheme_name_1"]
  	@today_date = Date.parse('2017-06-15')
  	@col = add_row
    p "qqqqqqqqqqqqqqqq"
  	p @col
  	p @purchase_date
  	p @inv_amt
  	p @scheme_name
  	p @today_date
  	@total_investment_amt = 0
  	@total_value = 0

  	for i in 1..(@@col)
      p "iiiiiiiiiii"
      i = i.to_s
      p i
  		purchase_date = Date.parse(params['date_#{i}'])
	  	inv_amt = params['amt_#{i}'].to_i
	  	scheme_name = params['scheme_name_#{i}']
	  	today_date = Date.parse('2017-06-15')
	  	@total_investment_amt += inv_amt
  		@total_value += calculate_nav(purchase_date, inv_amt, scheme_name, today_date)
      p "yessssssssssssssssssss"
      p @total_value
  	end
    
  end

  private

  def calculate_nav(purchase_date, inv_amt, scheme_name, today_date)
    p "2222222222222222"
  	scheme_old = NavHistory.where("scheme_name = ? and date = ?", scheme_name, purchase_date)[0]
  	nav_for_the_day = scheme_old.nav
  	shares = (inv_amt/nav_for_the_day).round(2)
  	scheme_current = NavHistory.where("scheme_name = ? and date = ?", scheme_name, today_date)[0]
  	nav_for_current_day = scheme_current.nav
  	investment_value = (shares * nav_for_current_day).ceil

  	return investment_value

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nav_helper.rb
module NavHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvestmentApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nav/calc_nav.js.erb
$("#output").html("<p><h4>Total Investment: <%= @total_investment_amt %></h4></p><p><h4>Current Value For The Investment: <%= @total_value %></h4></p>");

app/views/nav/index.html.erb
<style type="text/css">
	#container {
		width: 80%;
		margin: 0 auto;
	}
	.rTable {
	  	display: table;
	  	width: 100%;
	}
	.rTableRow {
	  	display: table-row;
	}
	.rTableCell {
	  	display: table-cell;
	  	padding: 10px 10px;
	  	border: 1px solid #999999;
	}
	.rTableHead {
	  	display: table-cell;
	  	padding: 10px 10px;
	  	border: 1px solid #999999;
	  	background-color: #00BF40;
	}
	
	
}
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.18/vue.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<h2>Portfolio</h2>
<div id="container">
<%= form_tag(nav_calc_nav_path, :method => "get", remote: true) do %>
	<div id="app">
		<div class="rTable" id="table1">
			<div class="rTableRow" id="row_0">
				<div class="rTableHead"><span style="font-weight: bold;">Scheme Amount</div>
				<div class="rTableHead"><span style="font-weight: bold;">Scheme Name</span></div>
				<div class="rTableHead"><span style="font-weight: bold;">Investment Date</span></div>
				</div>
			<div class="rTableRow" id="row_1">
				<div class="rTableCell"><input type="text" name="amt_1" placeholder="(Rs)" id = "amt_1"></div>
				<div class="rTableCell"><select name="scheme_name_1" id = "scheme_name_1"><option value="Axis Fixed Income Opportunities Fund - Regular Plan - Growth">Axis Fixed Income Opportunities Fund - Regular Plan - Growth</option><option value="Axis Regular Savings Fund - Quarterly Dividend Option"> Axis Regular Savings Fund - Quarterly Dividend Option</option><option value="Axis Gold Fund - Direct Plan - Growth"> Axis Gold Fund - Direct Plan - Growth option</option><option value="Axis Long Term Equity Fund - Direct Plan - Dividend option"> Axis Long Term Equity Fund - Direct Plan - Dividend option</option></select></div>
				<div class="rTableCell"><input type="date" name="date_1" id = "date_1"></div>
			</div>
		</div>

		
		<div id="example-1">
		<button class="glyphicon glyphicon-plus"  v-on:click="counter += 1" @click="addRow" ></button>
<!-- 		  <button class= "glyphicon glyphicon-plus"  v-on:click="counter += 1" "></button>
 -->		  
		  <p>The button above has been clicked {{ counter }} times.</p>
		</div>		
		<%= submit_tag "submit", :name => nil, remote: true, :id => "submit" %>
	</div>
	<% end %>
		
	<div id="output">
	
	</div>
</div>

<script >
	// $( "#add" ).click(function() {
 //  alert( "Handler for .click() called." );
	// 	$.ajax({
 //      type: "GET",
 //      url: "/nav/add_row",
 //      data: {}, 
 //      datatype:"json",
 //          complete: function() {},
 //          success: function (result) {
 //          	var col = parseInt(($('#table1 div.rTableRow:last-child')[0].id).match(/(\d+)/g)) + 1;
 //          	alert(col);
 //          	$( "#table1" ).append('<div class="rTableRow" id="row_'+col+'"></div><div class="rTableCell"><input type="text" name="amt_'+col+'" id = "amt_'+col+'" placeholder="(Rs)"></div><div class="rTableCell"><select name="scheme_name_'+col+'" id = "scheme_name_'+col+'"><option value="Axis Fixed Income Opportunities Fund - Regular Plan - Growth">Axis Fixed Income Opportunities Fund - Regular Plan - Growth</option><option value="Axis Regular Savings Fund - Quarterly Dividend Option"> Axis Regular Savings Fund - Quarterly Dividend Option</option><option value="Axis Gold Fund - Direct Plan - Growth option"> Axis Gold Fund - Direct Plan - Growth option</option><option value="Axis Long Term Equity Fund - Direct Plan - Dividend option"> Axis Long Term Equity Fund - Direct Plan - Dividend option</option></select></div><div class="rTableCell"><input type="date" name="date_'+col+'" id = "date_'+col+'"></div>');
 //          }
          	
	// });
	// });

	// $('#submit').click(function(){
	// 	// var col = parseInt(($('#table1 div.rTableRow:last-child')[0].id).match(/(\d+)/g)) + 1;
	// 	// alert(col);
	// 	// a = $('#amt_1').val();
	// 	// a1 = col;
	// 	// a1 = 
	// 	// var invest_amt = $('#id').val();
	// 	// event.preventDefault();
	// 	amt = $('#amt_1').val();
	// 	$.ajax({
	//       type: "GET",
	//       url: "/nav/calc_nav",
	//       data: {}, 
	//       datatype:"json",
 //          complete: function() {alert("completed");},
 //          success: function (result) {
 //          	alert("success");
 //         	$('#total').html(result.total_investment_amt);
 //         	 $('#current').html(result.total_value);
	// 	},
	// });
	// });

	var example1 = new Vue({
  el: '#example-1',
  data: {
    counter: 0
  }
})

</script>

	=======================================================================
	<div id="app1">
        <table class="table">
            <thead>
                <tr>
                    <td><strong>Title</strong></td>
                    <td><strong>Description</strong></td>
                    <td><strong>File</strong></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(row, index) in rows">

                    <td><input type="text" v-model="row.title"></td>
                    <td><input type="text" v-model="row.description"></td>
                    <td>
                        <label class="fileContainer">
                            {{row.file.name}}
                            <input type="file" @change="setFilename($event, row)" :id="index">
                        </label>
                    </td>
                    <td>
                        <a v-on:click="removeElement(index);" style="cursor: pointer">Remove</a>
                    </td>


                </tr>
            </tbody>
        </table>
        <div>
            <button class="button btn-primary" @click="addRow">Add row</button>
        </div>
    </div>

    <script type="text/javascript">
        var app = new Vue({
            el: "#app1",
            data: {
                rows: []
            },
            methods: {
                addRow: function() {
                    var elem = document.createElement('tr');
                    this.rows.push({
                        title: "",
                        description: "",
                        file: {
                            name: 'Choose File'
                        }
                    });
                },
                removeElement: function(index) {
                    this.rows.splice(index, 1);
                },
                setFilename: function(event, row) {
                    var file = event.target.files[0];
                    row.file = file
                }
            }
        });
    </script>